version: '2'

services:

  bibbox-postgres:
    image: postgres:latest
    container_name: bibbox-postgres
    environment:
      POSTGRES_USER:      §§POSTGRES_USER
      POSTGRES_PASSWORD:  §§POSTGRES_PASSWORD
      POSTGRES_DB:        §§POSTGRES_DB
    ports:
      - "5432:5432"
    depends_on:
      - bibbox-postgres-data
    volumes_from:
      - bibbox-postgres-data

  bibbox-adminer:
    image: adminer
    container_name: bibbox-adminer
    links:
      - bibbox-postgres:db
    depends_on:
      - bibbox-postgres
    ports:
      - "8065:8080"

  bibbox-postgres-data:
    image: busybox
    container_name: bibbox-postgres-data
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
