version: '3'
networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-postgres:
    image: postgres:latest
    container_name: §§INSTANCE-postgres
    environment:
      POSTGRES_USER:      §§POSTGRES_USER
      POSTGRES_PASSWORD:  §§POSTGRES_PASSWORD
      POSTGRES_DB:        §§POSTGRES_DB
   
    networks:
      - bibbox-default-network
    restart: always
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data


  §§INSTANCE-adminer:
    image: adminer
    container_name: §§INSTANCE-adminer
    links:
      - §§INSTANCE-postgres:db
    depends_on:
      - §§INSTANCE-postgres
    ports:
      - "8080:8080"
    networks:
      - bibbox-default-network
    restart: always

  
