version: '3'

services:

  bibbox-postgres:
    image: postgres:16.0
    container_name: bibbox-postgres
    environment:
      POSTGRES_USER:      §§POSTGRES_USER
      POSTGRES_PASSWORD:  §§POSTGRES_PASSWORD
      POSTGRES_DB:        §§POSTGRES_DB
    ports:
      - "5666:5666"
    

  bibbox-adminer:
    image: adminer
    container_name: bibbox-adminer
    links:
      - bibbox-postgres:db
    depends_on:
      - bibbox-postgres
    ports:
      - "8080:8080"
    networks:
      - bibbox-default-network
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    proxy:
      TYPE: PRIMARY
      URLPREFIX: bibbox-postgres
      TEMPLATE: default
      DISPLAYNAME: 'App Adminerproxy'

 
    
